tasks:
  - name: Start back-end
    before: cd server/study_smart
    init: make build
    command: make up
    openMode: split-left

  - name: Init data
    init: |
      gp ports await 8000
      sleep 40
      cd server/study_smart && make init
    openMode: split-right
ports:
  - port: 8000
    onOpen: ignore
    visibility: public